sudo: false
language:
  - python
  - node_js
before_script:
  - npm install
python:
  - 3.5
install:
  - pip install -r requirements.txt
scripts:
  - cd dream11/
  - scripyd &
  - cd ..
  - npm start &
  - curl http://localhost:6800/schedule.json -d project=default -d spider=linkspider